version: "3.8"

services:
  web:
    build:
      context: ./app
    container_name: taskmanager_ci_web
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: taskmanager_ci_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data_ci:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tester:
    build:
      context: .
    container_name: taskmanager_ci_tester
    depends_on:
      - web
    environment:
      - BASE_URL=http://web

volumes:
  db_data_ci:
