version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: taskmanager_web
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: taskmanager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: taskmanager_tester
    depends_on:
      - web
    environment:
      - BASE_URL=http://web
    volumes:
      - .:/app

volumes:
  db_data:
